### ISSUE TITLE
Scoring comments

### ISSUE THREAD

**Issue by obfuscurity** [obfuscurity/judy#14]
Multiple folks have requested a comment field for adding notes about their score on an abstract.

**Comment by patcable** [comment]
I may be looking at adding this over the weekend. I was going to ask -- how do you currently handle this for monitorama? group slack and put notes there?

**Comment by obfuscurity** [comment]
We don't, yet. This has been the one pain point I've really neglected. 😢

**Comment by obfuscurity** [comment]
Fixed by #28.
