### ISSUE TITLE
Where is .env.example?

### ISSUE THREAD

**Issue by jsindy** [obfuscurity/judy#21]
Where is .env.example?
cant seem to locate it.

**Comment by obfuscurity** [comment]
Hi @jsindy, it's a very simple file. I don't think it really needs formal documentation.

```
DATABASE_URL=postgres://127.0.0.1/judy
JUDY_AUTH=user1:pass1,user2:pass2
```

**Comment by jsindy** [comment]
absolutely agree, I thought it was for the database info. 

I am working on a Dockerfile https://gist.github.com/jsindy/32fec343597293284ad5

Unfortunately doing "bundle exec rake db:migrate:up" had no idea about the DB info. Not sure if I need a database.yml or where to put it.

**Comment by obfuscurity** [comment]
You don't *need* a database.yml file, and I've certainly never used one. You just need to make sure the `DATABASE_URL` is set accordingly. Now that you mention it, I don't think bundler reads those files, so you'll need to export `DATABASE_URL` or call it explicitly with the bundle command.

**Comment by jsindy** [comment]
will try, thanks!
