### ISSUE TITLE
Master seems broken

### ISSUE THREAD

**Issue by jsindy** [obfuscurity/judy#22]
Launching it in Heroku shows the same issue as building local.

When you create a new abstract it just goes to a blank page.

On my local build I see the error

21:48:54 web.1  | "PG::NotNullViolation: ERROR:  null value in column \"type\" violates not-null constraint\nDETAIL:  Failing row contains (2, title, body, 2, 1, null).\n"

Can you recommend a commit that is the lastest stable? Thanks!

**Comment by obfuscurity** [comment]
You're right, I forgot to add an `update` to the sample data to set the `type`. I'll fix that tonight.

**Comment by jsindy** [comment]
Thank you sir.

**Comment by jsindy** [comment]
We are going to be running this for a up coming conference and was curious what commit we should use? Master when fixed? tag v0.1.0? let me know what you suggest, thanks!

**Comment by obfuscurity** [comment]
Ok, you should be able to submit new abstracts from that form now. There are still a number of areas I'd like to improve (e.g. better tags/labels support) but I don't have any more time tonight. I need to have them done for our upcoming CFP review though, so you can probably expect them in the next week or so.

**Comment by obfuscurity** [comment]
https://github.com/obfuscurity/judy/releases/tag/v0.2.0
